AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for Cello DynamoDB table"

Parameters:
  TableName:
    Type: String
    Default: cello
    Description: Name of the DynamoDB table to create
    AllowedPattern: "^[a-zA-Z0-9_.-]+$"
    MaxLength: 255
    MinLength: 3

Resources:
  CelloTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      # No additional indexes required for our known access patterns
      # GlobalSecondaryIndexes: []

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref CelloTable
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt CelloTable.Arn

